name: Python Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run tests
        env:
          LEAN_LOG_LEVEL: 'NONE'
        run: pytest -q
